name: taskfull
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  google_fonts: ^6.2.1
animated_splash_screen:

  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.5.0 
  percent_indicator: ^4.2.3
  date_picker_timeline: ^1.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  equatable: ^2.0.5
  flex_color_scheme: ^7.2.0
  flutter_riverpod: ^2.3.6
  gap: ^3.0.1
  go_router: ^10.0.0
  intl: ^0.18.1
  path: ^1.8.3
  sqflite: ^2.3.0



  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - images/

  